apiVersion: v1
kind: Secret
metadata:
  name: homepage-secrets
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
type: Opaque
stringData:
  PIHOLE_API_KEY: "YOUR_API_KEY_HERE"
  OMV_USERNAME: "YOUR_OMV_USERNAME_HERE"
  OMV_PASSWORD: "YOUR_OMV_PASSWORD_HERE"
