apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Network Services:
        - PiHole:
            href: https://pihole.teamnub.lan/admin
            description: Network-wide ad blocking
            widget:
              type: pihole
              url: https://pihole.teamnub.lan
              version: 6
              key: {{HOMEPAGE_VAR_PIHOLE_API_KEY}}

    - File Services:
        - OpenMediaVault:
            href: http://omv.teamnub.lan/
            description: Network Attached Storage
            widget:
              type: openmediavault
              url: http://omv.teamnub.lan/
              username: {{HOMEPAGE_VAR_OMV_USERNAME}}
              password: {{HOMEPAGE_VAR_OMV_PASSWORD}}
              method: services.getStatus

    - My Second Group:
        - My Second Service:
            href: http://localhost/
            description: Homepage is the best

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""